config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :nannies
  resources :clients
  resources :job_posts

  get "/", to: "home#index"
  get "/families", to: "home#family_land"
  get "/nannsies", to: "home#nanny_land"
  get "/fee_schedule", to: "home#fee_schedule"
  get "/services", to: "home#services"
  get "/admin", to: "admin#dashboard"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/job_post.rb
class JobPost < ApplicationRecord
end

app/models/nanny.rb
class Nanny < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_admin!

  def dashboard
  end

  def admin
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :spouse_first_name, :email, :phone, :alt_phone, :street, :street2, :city, :state, :zip, :profession, :partner_profession, :needed_service, :num_of_kids, :names_and_ages_kids, :special_needs, :medical_condition, :pets, :pet_care, :family_schedule, :household_tasks, :fam_philosophy, :playdates)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def family_land
  end

  def nanny_land
  end

  def fee_schedule
  end

  def services
  end
  
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  before_action :authenticate_admin!, :set_job_post, only: [:show, :edit, :update, :destroy]

  # GET /job_posts
  # GET /job_posts.json
  def index
    @job_posts = JobPost.all
  end

  # GET /job_posts/1
  # GET /job_posts/1.json
  def show
  end

  # GET /job_posts/new
  def new
    @job_post = JobPost.new
  end

  # GET /job_posts/1/edit
  def edit
  end

  # POST /job_posts
  # POST /job_posts.json
  def create
    @job_post = JobPost.new(job_post_params)

    respond_to do |format|
      if @job_post.save
        format.html { redirect_to @job_post, notice: 'Job post was successfully created.' }
        format.json { render :show, status: :created, location: @job_post }
      else
        format.html { render :new }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_posts/1
  # PATCH/PUT /job_posts/1.json
  def update
    respond_to do |format|
      if @job_post.update(job_post_params)
        format.html { redirect_to @job_post, notice: 'Job post was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_post }
      else
        format.html { render :edit }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_posts/1
  # DELETE /job_posts/1.json
  def destroy
    @job_post.destroy
    respond_to do |format|
      format.html { redirect_to job_posts_url, notice: 'Job post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_post
      @job_post = JobPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_post_params
      params.require(:job_post).permit(:family_name, :headline, :location, :work_type, :hiring_date, :description)
    end
end

app/controllers/nannies_controller.rb
class NanniesController < ApplicationController
  before_action :set_nanny, only: [:show, :edit, :update, :destroy]

  # GET /nannies
  # GET /nannies.json
  def index
    @nannies = Nanny.all
  end

  # GET /nannies/1
  # GET /nannies/1.json
  def show
  end

  # GET /nannies/new
  def new
    @nanny = Nanny.new
  end

  # GET /nannies/1/edit
  def edit
  end

  # POST /nannies
  # POST /nannies.json
  def create
    @nanny = Nanny.new(nanny_params)

    respond_to do |format|
      if @nanny.save
        format.html { redirect_to @nanny, notice: 'Nanny was successfully created.' }
        format.json { render :show, status: :created, location: @nanny }
      else
        format.html { render :new }
        format.json { render json: @nanny.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nannies/1
  # PATCH/PUT /nannies/1.json
  def update
    respond_to do |format|
      if @nanny.update(nanny_params)
        format.html { redirect_to @nanny, notice: 'Nanny was successfully updated.' }
        format.json { render :show, status: :ok, location: @nanny }
      else
        format.html { render :edit }
        format.json { render json: @nanny.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nannies/1
  # DELETE /nannies/1.json
  def destroy
    @nanny.destroy
    respond_to do |format|
      format.html { redirect_to nannies_url, notice: 'Nanny was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nanny
      @nanny = Nanny.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nanny_params
      params.require(:nanny).permit(:first_name, :last_name, :email, :street_address, :address2, :city, :state, :zipcode, :time_at_cur_addre, :phone, :desired_hrs, :desired_territory, :desired_wage, :us_citizen, :work_permit, :gc_num, :yrs_in_usa, :have_dl, :dl_number, :dl_state, :yrs_driving, :own_car, :make_model, :use_for_work, :date_available, :sunday_avail, :monday_avail, :tuesday_avail, :wednesday_avail, :thursday_avail, :friday_avail, :saturday_avail, :one_year_min_commit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/nannies_helper.rb
module NanniesHelper
end

app/views/admin/dashboard.html.erb
<br>
<br>
<br>
<br>
<br>
<div class='jumbotron' align='center'><h1>Admin Dashboard</h1></div>
<br>
<br>
<br>

<div align='center'><h1><%= link_to 'See all Families ', clients_path %></h1></div>
 <br>
 <br>



<div align='center'><h1><%= link_to 'See All Nannies', nannies_path %></h1></div>

<br>
<br>

<div align='center'><h1><%= link_to 'See All Job Posts', job_posts_path %></h1></div>

<br>
<br>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>



<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<br>
<br>
<div class='jumbotron' align='center'><h1>Families</h1></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= link_to 'View', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<br>
<br>
<div align='center'>
  <%= link_to 'New Family', new_client_path %>
  <br>
  <br>
  <br>
  <%= link_to 'Back to Dashboard', admin_path %>
</div>




  
      

app/views/clients/new.html.erb
<div class='jumbotron'><strong>New Family</strong></div>
<br>
<br>

<%= render 'form', client: @client %>

<%= link_to 'Back', families_path %>

app/views/clients/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Spouse first name:</strong>
  <%= @client.spouse_first_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Alt phone:</strong>
  <%= @client.alt_phone %>
</p>

<p>
  <strong>Street:</strong>
  <%= @client.street %>
</p>

<p>
  <strong>Street2:</strong>
  <%= @client.street2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @client.profession %>
</p>

<p>
  <strong>Partner profession:</strong>
  <%= @client.partner_profession %>
</p>

<p>
  <strong>Needed service:</strong>
  <%= @client.needed_service %>
</p>

<p>
  <strong>Num of kids:</strong>
  <%= @client.num_of_kids %>
</p>

<p>
  <strong>Names and ages kids:</strong>
  <%= @client.names_and_ages_kids %>
</p>

<p>
  <strong>Special needs:</strong>
  <%= @client.special_needs %>
</p>

<p>
  <strong>Medical condition:</strong>
  <%= @client.medical_condition %>
</p>

<p>
  <strong>Pets:</strong>
  <%= @client.pets %>
</p>

<p>
  <strong>Pet care:</strong>
  <%= @client.pet_care %>
</p>

<p>
  <strong>Family schedule:</strong>
  <%= @client.family_schedule %>
</p>

<p>
  <strong>Household tasks:</strong>
  <%= @client.household_tasks %>
</p>

<p>
  <strong>Fam philosophy:</strong>
  <%= @client.fam_philosophy %>
</p>

<p>
  <strong>Playdates:</strong>
  <%= @client.playdates %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/home/family_land.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 align='center'>Thanks for your interest in Super Nanny Agency!</h1>

<div align='center'>
  <h1><%= link_to 'Family Sign Up', new_client_path %></h1>
</div>


<h2>BACKGROUND CHECKS AND SCREENING</h2>
<p>Super Nanny Agency offers an extensive and thorough investigation into the candidate's experience and work history.</p>

<p>Super Nanny Agency starts the interviewing process with a telephone interview. We make sure the nanny has all the necessary requirements that the agency requires.</p>
<p>With every childcare position Super Nanny Agency conducts an in depth face-to-face interview. We then make the decision if the candidate is right for our agency.</p>
<p>We will conduct a criminal check in every state and county.</p>
<p>We will conduct a motor vehicle check for tickets, accident and suspensions.</p>
<p>Super Nanny Agency candidates must be CPR and First Aid certified.</p>
<h2>FAMILY PACKET</h2>
<p>The reason Super Nanny Agency is so unique is that we provide you with all the information you need to keep and enjoy your nanny. We provide every family who decide to work with our agency a packed of useful information.</p>

<h2>FAMILY PACKED INCLUDES:</h2>
<p>Background and Screening Process</p>
<p>Nanny Salary Information</p>
<p>Payroll and Tax Information</p>
<p>Copy of Nanny Application</p>
<p>Family/Nanny Agreement</p>
<p>Interview Questions</p>
<p>Guarantee Information</p>
<h2>FAQS</h2>
<h2>HOW DO I KNOW WHAT TO PAY MY NANNY?</h2>
<p>There are many different factors to consider when paying your nanny. How much childcare experience does your nanny have? Is your nanny responsible for any household chores? Do you have more than one child? All of these things should be considered when determining what you are going to pay your nanny. Contact our agency for more precise numbers.</p>

<h2>DO YOU GIVE VACATION TIME?</h2>
<p>Most families will give their nanny two weeks vacation per year. Some families give one week after six months and one week after the first year. Discuss with your nanny whether or not they need to take their vocation at the dame time as your family vocation.</p>

<h2>SHOULD MY NANNY GET PAID HOLIDAYS?</h2>
<p>I recommend giving your nanny the same paid holidays as your company gives you. Whatever you may decide, make sure you communicate this information with your nanny.</p>

<h2>HOW MANY SICK DAYS SHOULD MY NANNY GET?</h2>
<p>I recommend giving your nanny sick days consistent with what your company gives you. Again, be sure to communicate this information with your nanny.</p>

<h2>SHOULD WE PAY OVER TIME?</h2>
<p>If your nanny's schedule is until 6:00pm and you arrive at 6:30, your nanny should be compensated for the extra time. Some nannies would rather be paid for the extra time and some would have that extra time off another day. The decision should be made between you and your nanny.</p>

<h2>WHAT DO I PAY IF WE NEED OUR NANNY OVER NIGHT?</h2>
<p>Paying your nanny to spend the night is a bit tricky. Some nannies want to get paid for each hour and some will give you an amount for that night. Remember, this amount is in addition to their regular daily pay. Make sure you and your nanny discuss this.</p>

<h2>WHAT DO WE PAY OUR NANNY TO GO ON VACATION WITH US?</h2>
<p>I recommend you pay your nanny her regular salary and an overnight amount. If your nanny is working harder on vacation, this should be taken into consideration. This is one of the biggest reason nannies don't stay with a family. Remember, this is YOUR vacation, not nanny's. This is work for your nanny.</p>
<br>
<br>
<br>

app/views/home/index.html.erb
<body>

<br>
<br>
<br>
 
<br>
<br>
<div class="bg-color-sky-light">
  <div style='background-color:#d3ede2' class="content-lg container">
    <div align='center'>
      <strong class="display-3" style='color:#f0bfff'>Super Nanny Agency</strong>
    </div>

    
    <br>
    <br>
    <br>
      <h1><%= link_to 'Families', families_path %></h1><br><br>
      
      <h1><%= link_to 'Nannies', nannsies_path %></h1><br><br>
      
      <h1><%= link_to 'Services', services_path %></h1><br><br>
      
      <h1><%= link_to 'Fee Schedule', fee_schedule_path %></h1><br><br>
    </div>



  </div>
</div>

</body>

app/views/home/nanny_land.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 align='center'>Thank you for your interest in Super Nanny Agency!</h1>
<br>
<br>
<br>
<br>
<br>
<div align='center'>
  <h1><%= link_to 'Nanny Application', new_nanny_path %></h1>
</div>
<br>
<p class="lead">Please click on "Nanny Application" above to take the first step. We look forward to working with you and helping you find your perfect position. You will receive a copy of your application as confirmation of submission. Your local placement provider will be in touch with you to schedule an interview when your application is received.</p>

<h2>NANNIES REQUIREMENTS</h2>
<p>Background checks</p>
<p>Criminal check in every county and state</p>
<p>Motor vehicle check for suspensions, tickets and accidents</p>
<p>Reference checks</p>
<p>Verification of employment and evaluation of performance</p>
<p>Phone interview with every previous childcare employer</p>
<p>Phone interview with all references</p>
<br>
<h2>TRAINING COURSES</h2>
<p>CPR certification</p>
<p>First AID training</p>
<br>
<h2>MINIMUM REQUIREMENTS</h2>
<p>References from previous nanny position</p>
<p>GED</p>
<p>Legal documentation</p>
<p>Face to face interview with agency</p>
<br>
<h2>NANNY PACKET</h2>
<p>Super Nanny Agency will provide all of our nannies with an informational packet. This packet will help you look at all angles of being a professional nanny.</p>

<h2>NANNY PACKET INCLUDES:</h2>
<p>CPR and First Aid information</p>
<p>Tax information</p>
<p>Family/Nanny agreement</p>
<p>Interview questions</p>
<p>Copy of nanny contract</p>
<p>Background and screening process</p>
<br>
<br>

app/views/job_posts/edit.html.erb
<h1>Editing Job Post</h1>

<%= render 'form', job_post: @job_post %>

<%= link_to 'Show', @job_post %> |
<%= link_to 'Back', job_posts_path %>

app/views/job_posts/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div class='jumbotron' align='center'>
<h1>Job Posts</h1></div>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Family name</th>
      <th>Headline</th>
      <th>Location</th>
      <th>Work Type</th>
      <th>Hiring date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_posts.each do |job_post| %>
      <tr>
        <td><%= job_post.family_name %></td>
        <td><%= job_post.headline %></td>
        <td><%= job_post.location %></td>
        <td><%= job_post.work_type %></td>
        <td><%= job_post.hiring_date %></td>
        <td><%= job_post.description %></td>
        <td><%= link_to 'Show', job_post %></td>
        <td><%= link_to 'Edit', edit_job_post_path(job_post) %></td>
        <td><%= link_to 'Destroy', job_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<br>
<br>
<div align='center'>
<%= link_to 'New Job Post', new_job_post_path %>
<br>
<br>
<br>
  <%= link_to 'Back to Dashboard', admin_path %>
</div>

app/views/job_posts/new.html.erb
<h1>New Job Post</h1>

<%= render 'form', job_post: @job_post %>

<%= link_to 'Back', job_posts_path %>

app/views/job_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Family name:</strong>
  <%= @job_post.family_name %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @job_post.headline %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job_post.location %>
</p>

<p>
  <strong>Type:</strong>
  <%= @job_post.work_type %>
</p>

<p>
  <strong>Hiring date:</strong>
  <%= @job_post.hiring_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job_post.description %>
</p>

<%= link_to 'Edit', edit_job_post_path(@job_post) %> |
<%= link_to 'Back', job_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Top Nanny</title>
    <%= csrf_meta_tags %>

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <nav class="navbar navbar-default">
      <h5><a style='color:#f0bfff' href="/">Super Nanny Agency</a></h5>
    
      <p class="navbar-text pull-right">
      <% if admin_signed_in? %>
        Logged in as <strong><%= current_admin.email %></strong>. 
        <%= link_to 'Dashboard', admin_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Admin", new_admin_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>
    </nav


    <%= yield %>

  </body>
  <footer>
    <br>
    
    <div align='center'>Super Nanny Agency | t: 773-818-8556 | e: walladap@gmail.com</div>
    <br>
    <br>  
    <br>
  </footer>
</html>

app/views/nannies/edit.html.erb
<h1>Editing Nanny</h1>

<%= render 'form', nanny: @nanny %>

<%= link_to 'Show', @nanny %> |
<%= link_to 'Back', nannies_path %>

app/views/nannies/index.html.erb
<br>
<br>
<div class='jumbotron' align='center'>
<h1>Nannies</h1>
</div>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nannies.each do |nanny| %>
      <tr>
        <td><%= nanny.first_name %></td>
        <td><%= nanny.last_name %></td>
        <td><%= link_to 'View', nanny %></td>
        <td><%= link_to 'Edit', edit_nanny_path(nanny) %></td>
        <td><%= link_to 'Delete', nanny, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<br>
<div align='center'>
  <%= link_to 'New Nanny', new_nanny_path %>
  <br>
  <br>
  <br>
  <%= link_to 'Back to Dashboard', admin_path %>
</div>

app/views/nannies/new.html.erb
<h1>New Nanny</h1>

<%= render 'form', nanny: @nanny %>

<%= link_to 'Back', nannsies_path %>

app/views/nannies/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @nanny.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @nanny.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @nanny.email %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @nanny.street_address %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @nanny.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @nanny.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @nanny.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @nanny.zipcode %>
</p>

<p>
  <strong>Time at cur addre:</strong>
  <%= @nanny.time_at_cur_addre %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @nanny.phone %>
</p>

<p>
  <strong>Desired hrs:</strong>
  <%= @nanny.desired_hrs %>
</p>

<p>
  <strong>Desired territory:</strong>
  <%= @nanny.desired_territory %>
</p>

<p>
  <strong>Desired wage:</strong>
  <%= @nanny.desired_wage %>
</p>

<p>
  <strong>Us citizen:</strong>
  <%= @nanny.us_citizen %>
</p>

<p>
  <strong>Work permit:</strong>
  <%= @nanny.work_permit %>
</p>

<p>
  <strong>Gc num:</strong>
  <%= @nanny.gc_num %>
</p>

<p>
  <strong>Yrs in usa:</strong>
  <%= @nanny.yrs_in_usa %>
</p>

<p>
  <strong>Have dl:</strong>
  <%= @nanny.have_dl %>
</p>

<p>
  <strong>Dl number:</strong>
  <%= @nanny.dl_number %>
</p>

<p>
  <strong>Dl state:</strong>
  <%= @nanny.dl_state %>
</p>

<p>
  <strong>Yrs driving:</strong>
  <%= @nanny.yrs_driving %>
</p>

<p>
  <strong>Own car:</strong>
  <%= @nanny.own_car %>
</p>

<p>
  <strong>Make model:</strong>
  <%= @nanny.make_model %>
</p>

<p>
  <strong>Use for work:</strong>
  <%= @nanny.use_for_work %>
</p>

<p>
  <strong>Date available:</strong>
  <%= @nanny.date_available %>
</p>

<p>
  <strong>Sunday avail:</strong>
  <%= @nanny.sunday_avail %>
</p>

<p>
  <strong>Monday avail:</strong>
  <%= @nanny.monday_avail %>
</p>

<p>
  <strong>Tuesday avail:</strong>
  <%= @nanny.tuesday_avail %>
</p>

<p>
  <strong>Wednesday avail:</strong>
  <%= @nanny.wednesday_avail %>
</p>

<p>
  <strong>Thursday avail:</strong>
  <%= @nanny.thursday_avail %>
</p>

<p>
  <strong>Friday avail:</strong>
  <%= @nanny.friday_avail %>
</p>

<p>
  <strong>Saturday avail:</strong>
  <%= @nanny.saturday_avail %>
</p>

<p>
  <strong>One year min commit:</strong>
  <%= @nanny.one_year_min_commit %>
</p>

<%= link_to 'Edit', edit_nanny_path(@nanny) %> |
<%= link_to 'Back', nannies_path %>